import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("help", "routes/help.tsx"),
  // route("rewards", "routes/rewards.tsx"),
  route("brand/:slug", "routes/brand.$slug.tsx"),
  route("products", "routes/products.tsx"),
  route("product/:slug", "routes/product.$slug.tsx"),
  route("track", "routes/track.tsx"),
  route("order/:id", "routes/order.$id.tsx"),
  route("cart", "routes/cart.tsx"),
  route("cart/add", "routes/cart.add.tsx"),
  route("cart/update", "routes/cart.update.tsx"),
  route("cart/coupon", "routes/cart.coupon.tsx"),
  route("checkout", "routes/checkout.tsx"),
  route("checkout/coupon", "routes/checkout.coupon.tsx"),
  route("checkout/update", "routes/checkout.update.tsx"),
  route("checkout/:id", "routes/checkout.$id.tsx"),
  route("email/subscribe", "routes/email.subscribe.tsx"),
  route("legal/privacy", "routes/legal.privacy.tsx"),
  route("legal/refund", "routes/legal.refund.tsx"),
  route("legal/shipping", "routes/legal.shipping.tsx"),
  route("legal/terms", "routes/legal.terms.tsx"),
  route("sitemap.xml", "routes/[sitemap.xml].tsx"),
] satisfies RouteConfig;
